language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - 7.0
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

env:
    - TCPDF_PACKAGE="tecnickcom/tcpdf"    TCPDF_VERSION="*"
    - TCPDF_PACKAGE="tecnickcom/tcpdf"    TCPDF_VERSION="6.1.x"
    - TCPDF_PACKAGE="onigoetz/fpdi_tcpdf" TCPDF_VERSION="*"

install:
    - composer self-update
    - rm -rf composer.json composer.lock
    - cp build/travis.composer.json composer.json
    - composer install --dev
    - echo ${TCPDF_PACKAGE}:${TCPDF_VERSION}
    - composer require ${TCPDF_PACKAGE}:${TCPDF_VERSION}
    - composer show -i

script:
    - ./vendor/bin/phpunit --configuration ./build/travis.phpunit.xml

after_script:
    - if [ $TRAVIS_JOB_ID == "1" ]; then ./vendor/bin/test-reporter --coverage-report=./tests/report/clover.xml; fi

addons:
    code_climate:
        repo_token: 913ac39b3783061de84315a48dcd0dfdc9bb8cc0f95c342df840608734336ea7
