language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - 7.0
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

env:
    - TCPDF_PACKAGE="tecnickcom/tcpdf"    TCPDF_VERSION="*"
    - TCPDF_PACKAGE="tecnickcom/tcpdf"    TCPDF_VERSION="6.1.x"
    - TCPDF_PACKAGE="onigoetz/fpdi_tcpdf" TCPDF_VERSION="*"

install:
    - composer self-update
    - rm -rf composer.json composer.lock
    - cp build/travis.composer.json composer.json
    - composer install --dev
    - echo ${TCPDF_PACKAGE}:${TCPDF_VERSION}
    - composer require ${TCPDF_PACKAGE}:${TCPDF_VERSION}
    - composer show -i

script:
    - ./vendor/bin/phpunit --configuration ./build/travis.phpunit.xml

after_script:
    - echo "TRAVIS_JOB_ID = $TRAVIS_JOB_ID"
    - echo "CI = $CI"
    - echo "TRAVIS = $TRAVIS"
    - echo "CONTINUOUS_INTEGRATION = $CONTINUOUS_INTEGRATION"
    - echo "DEBIAN_FRONTEND = $DEBIAN_FRONTEND"
    - echo "HAS_JOSH_K_SEAL_OF_APPROVAL = $HAS_JOSH_K_SEAL_OF_APPROVAL"
    - echo "USER = $USER"
    - echo "HOME = $HOME"
    - echo "LANG = $LANG"
    - echo "LC_ALL = $LC_ALL"
    - echo "RAILS_ENV = $RAILS_ENV"
    - echo "RACK_ENV = $RACK_ENV"
    - echo "MERB_ENV = $MERB_ENV"
    - echo "JRUBY_OPTS = $JRUBY_OPTS"
    - echo "JAVA_HOME = $JAVA_HOME"
    - echo "TRAVIS_BRANCH = $TRAVIS_BRANCH"
    - echo "TRAVIS_BUILD_DIR = $TRAVIS_BUILD_DIR"
    - echo "TRAVIS_BUILD_ID = $TRAVIS_BUILD_ID"
    - echo "TRAVIS_BUILD_NUMBER = $TRAVIS_BUILD_NUMBER"
    - echo "TRAVIS_COMMIT = $TRAVIS_COMMIT"
    - echo "TRAVIS_COMMIT_RANGE = $TRAVIS_COMMIT_RANGE"
    - echo "TRAVIS_JOB_ID = $TRAVIS_JOB_ID"
    - echo "TRAVIS_JOB_NUMBER = $TRAVIS_JOB_NUMBER"
    - echo "TRAVIS_PULL_REQUEST = $TRAVIS_PULL_REQUEST"
    - echo "TRAVIS_SECURE_ENV_VARS = $TRAVIS_SECURE_ENV_VARS"
    - echo "TRAVIS_REPO_SLUG = $TRAVIS_REPO_SLUG"
    - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
    - echo "TRAVIS_TAG = $TRAVIS_TAG"
    - echo "TRAVIS_DART_VERSION = $TRAVIS_DART_VERSION"
    - echo "TRAVIS_GO_VERSION = $TRAVIS_GO_VERSION"
    - echo "TRAVIS_HAXE_VERSION = $TRAVIS_HAXE_VERSION"
    - echo "TRAVIS_JDK_VERSION = $TRAVIS_JDK_VERSION"
    - echo "TRAVIS_JULIA_VERSION = $TRAVIS_JULIA_VERSION"
    - echo "TRAVIS_NODE_VERSION = $TRAVIS_NODE_VERSION"
    - echo "TRAVIS_OTP_RELEASE = $TRAVIS_OTP_RELEASE"
    - echo "TRAVIS_PERL_VERSION = $TRAVIS_PERL_VERSION"
    - echo "TRAVIS_PHP_VERSION = $TRAVIS_PHP_VERSION"
    - echo "TRAVIS_PYTHON_VERSION = $TRAVIS_PYTHON_VERSION"
    - echo "TRAVIS_R_VERSION = $TRAVIS_R_VERSION"
    - echo "TRAVIS_RUBY_VERSION = $TRAVIS_RUBY_VERSION"
    - echo "TRAVIS_RUST_VERSION = $TRAVIS_RUST_VERSION"
    - echo "TRAVIS_SCALA_VERSION = $TRAVIS_SCALA_VERSION"
    - echo "TRAVIS_XCODE_SDK = $TRAVIS_XCODE_SDK"
    - echo "TRAVIS_XCODE_SCHEME = $TRAVIS_XCODE_SCHEME"
    - echo "TRAVIS_XCODE_PROJECT = $TRAVIS_XCODE_PROJECT"
    - echo "TRAVIS_XCODE_WORKSPACE = $TRAVIS_XCODE_WORKSPACE"
    - if [ $TRAVIS_JOB_ID == "1" ]; then ./vendor/bin/test-reporter --coverage-report=./tests/report/clover.xml; else echo "Build was not elected to send code coverage report to Code Climate"; fi

addons:
    code_climate:
        repo_token: 913ac39b3783061de84315a48dcd0dfdc9bb8cc0f95c342df840608734336ea7
